node {
   stage('Source code update') {
      git([url: 'https://github.com/sh-ogawa/auto-test-demo.git', branch: 'sonar'])
   }
   stage('Analyzing source code.') {
      bat 'mvn clean jacoco:prepare-agent test jacoco:report -e | echo "ignore failure"'
      bat 'mvn sonar:sonar -e'
   }
}